### ISSUE TITLE
tile border not drawn correctly

### ISSUE THREAD

**Issue by npisanti** [brinoausrino/ofxOrnament#1]
hi! thanks for the addon, i'm really loving it. But i noticed some pixels where white during the rendering. 
I set the background to green and i blacked my cam so you can see better that some pixels at the tiles border are not drawn by the shader:

![ornament_glitch](https://cloud.githubusercontent.com/assets/9903661/23586938/11d6f640-01a1-11e7-9464-3d0f252f032d.png)

i'm using the addon with oF 0.9.7 on debian, with intel HD as graphic card.

thanks in advance!

**Comment by brinoausrino** [comment]
Ok, this should be fixed. Perhaps you may check if it works for you. Thanks for trying out the addon :)

**Comment by npisanti** [comment]
it improved a lot but still there are some undrawn pixels, in some groups it is more evident, in most of the groups it is just the center of the tiles conjunction

![unnamed window_001](https://cloud.githubusercontent.com/assets/9903661/24199004/66ed27d4-0f08-11e7-9dd8-dcc6c8fbf0fa.png)

**Comment by brinoausrino** [comment]
Nicola, you may try it again? I now did some hacking (using an ornament tile of 1px smaller) to solve the final undrawn pixels. 
Hopefully it works for you now as well :)

**Comment by npisanti** [comment]
Now it is working perfectly! thanks!
